/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'watchId' : bigint, 'quantity' : bigint }
export interface Watch {
  'id' : bigint,
  'movement' : string,
  'caseSize' : bigint,
  'name' : string,
  'description' : string,
  'waterResistance' : string,
  'brand' : string,
  'priceCents' : bigint,
  'material' : string,
}
export interface _SERVICE {
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getAllWatches' : ActorMethod<[], Array<Watch>>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCartTotalCents' : ActorMethod<[], bigint>,
  'getWatch' : ActorMethod<[bigint], Watch>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];