/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Watch = IDL.Record({
  'id' : IDL.Nat,
  'movement' : IDL.Text,
  'caseSize' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'waterResistance' : IDL.Text,
  'brand' : IDL.Text,
  'priceCents' : IDL.Nat,
  'material' : IDL.Text,
});
export const CartItem = IDL.Record({
  'watchId' : IDL.Nat,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getAllWatches' : IDL.Func([], [IDL.Vec(Watch)], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCartTotalCents' : IDL.Func([], [IDL.Nat], ['query']),
  'getWatch' : IDL.Func([IDL.Nat], [Watch], ['query']),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Watch = IDL.Record({
    'id' : IDL.Nat,
    'movement' : IDL.Text,
    'caseSize' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'waterResistance' : IDL.Text,
    'brand' : IDL.Text,
    'priceCents' : IDL.Nat,
    'material' : IDL.Text,
  });
  const CartItem = IDL.Record({ 'watchId' : IDL.Nat, 'quantity' : IDL.Nat });
  
  return IDL.Service({
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getAllWatches' : IDL.Func([], [IDL.Vec(Watch)], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCartTotalCents' : IDL.Func([], [IDL.Nat], ['query']),
    'getWatch' : IDL.Func([IDL.Nat], [Watch], ['query']),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };